// --------------------------------------------------------------------------------------------------------------------
// <copyright file="pagePresetGeneralReadme.cs" company="imbVeles" >
//
// Copyright (C) 2018 imbVeles
//
// This program is free software: you can redistribute it and/or modify
// it under the +terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
// </copyright>
// <summary>
// Project: imbSCI.Reporting
// Author: Goran Grubic
// ------------------------------------------------------------------------------------------------------------------
// Project web site: http://blog.veles.rs
// GitHub: http://github.com/gorangrubic
// Mendeley profile: http://www.mendeley.com/profiles/goran-grubi2/
// ORCID ID: http://orcid.org/0000-0003-2673-9471
// Email: hardy@veles.rs
// </summary>
// ------------------------------------------------------------------------------------------------------------------
namespace imbSCI.Reporting.meta.presets.servicepages
{
    using imbSCI.Core.extensions.enumworks;
    using imbSCI.Data.enums.fields;
    using imbSCI.Reporting.enums;
    using imbSCI.Reporting.meta.page;

    /// <summary>
    /// META structure with general readme.md diagnostic output
    /// </summary>
    /// \ingroup_disabled docServicePage
    public class pagePresetGeneralReadme : metaServicePage
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="pagePresetGeneralReadme"/> class.
        /// </summary>
        public pagePresetGeneralReadme() : base("General purpose ReadMe content describing report folder/page/item", "Read Me - General info", "readme", metaServicePagePosition.atBeginning.ToInt32())
        {
            header.name = "General Readme : Project[".t(templateFieldBasic.sci_projectname) + ("\\@").t(templateFieldBasic.sci_projectpath);
            header.description = "Type: ".t(templateFieldBasic.page_type) + (" - ").t(templateFieldBasic.path_file) + (" - TPC:").t(templateFieldBasic.self_plc);

            footer.bottomLine = "Autogenerated: ".t(templateFieldBasic.sys_date) + (" ").t(templateFieldBasic.sys_time) + (" - mem.alloc: ").t(templateFieldBasic.sys_mem) + (" - threads: ").t(templateFieldBasic.sys_threads);
        }
    }
}